all:
	g++ -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 -Winit-self -Wmissing-declarations -Wmissing-include-dirs -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-conversion -Wsign-promo -Wstrict-overflow=5 -Wswitch-default -Wundef -Wno-unused --std=c++14 int128test.cpp -o int128test -Wall -Wextra -ggdb -I..  -DMAIN
	./int128test 

